src/Entity/Archive.php
<?php

namespace App\Entity;

use App\Repository\ArchiveRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use DateTime;

#[ORM\Entity(repositoryClass: ArchiveRepository::class)]
class Archive
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message:"le path d'image ne doit etre vide")]
    private ?string $image = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message:"la description ne doit etre vide")]
    private ?string $description = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]

    
    public ?\DateTimeInterface $date_creation = null;

    #[ORM\ManyToOne(inversedBy: 'id_archives')]
    #[ORM\JoinColumn(name:"idT", referencedColumnName:"id")]
    
    private ?Travail $idT = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): static
    {
        $this->image = $image;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getDateCreation(): ?\DateTimeInterface
    {
        return $this->date_creation;
    }

    public function setDateCreation(\DateTimeInterface $date_creation): static
    {
        $this->date_creation = $date_creation ;

        return $this;
    }

    public function getIdT(): ?Travail
    {
        return $this->idT;
    }

    public function setIdT(?Travail $idT): static
    {
        $this->idT = $idT;

        return $this;
    }

 
}

src/Controller/ClientArchiveController.php
<?php

namespace App\Controller;
use App\Entity\PdfGeneratorService;
use App\Entity\Archive;
use App\Form\Archive1Type;
use App\Repository\ArchiveRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/client/archive')]
class ClientArchiveController extends AbstractController
{
    #[Route('/', name: 'app_client_archive_index', methods: ['GET'])]
    public function index(ArchiveRepository $archiveRepository): Response
    {
        return $this->render('client_archive/index.html.twig', [
            'archives' => $archiveRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_client_archive_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $archive = new Archive();
        $form = $this->createForm(Archive1Type::class, $archive);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($archive);
            $entityManager->flush();

            return $this->redirectToRoute('app_client_archive_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('client_archive/new.html.twig', [
            'archive' => $archive,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_client_archive_show', methods: ['GET'])]
    public function show(Archive $archive): Response
    {
        return $this->render('client_archive/show.html.twig', [
            'archive' => $archive,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_client_archive_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Archive $archive, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(Archive1Type::class, $archive);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_client_archive_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('client_archive/edit.html.twig', [
            'archive' => $archive,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_client_archive_delete', methods: ['POST'])]
    public function delete(Request $request, Archive $archive, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$archive->getId(), $request->request->get('_token'))) {
            $entityManager->remove($archive);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_client_archive_index', [], Response::HTTP_SEE_OTHER);
    }
    #[Route('/pdf/reservation', name: 'generator_service_reservation')]
    public function pdfEvenement(): Response
    {
        $archive= $this->getDoctrine()
            ->getRepository(Archive::class)
            ->findAll();



        $html =$this->renderView('mpdf/index.html.twig', ['archives' => $archive]);
        $pdfGeneratorService=new PdfGeneratorService();
        $pdf = $pdfGeneratorService->generatePdf($html);

        return new Response($pdf, 200, [
            'Content-Type' => 'application/pdf',
            'Content-Disposition' => 'inline; filename="document.pdf"',
        ]);

}



}

templates/client_archive/_delete_form.html.twig
<form method="post" action="{{ path('app_client_archive_delete', {'id': archive.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ archive.id) }}">
    <button class="btn">Delete</button>
</form>

templates/client_archive/_form.html.twig
{{ form_start(form,{'attr': {'novalidate': 'novalidate'}} ) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/client_archive/edit.html.twig
{% extends 'front.html.twig' %}

{% block title %}Edit Archive{% endblock %}

{% block body %}
    <h1>Edit Archive</h1>

    {{ include('client_archive/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_client_archive_index') }}">back to list</a>

    {{ include('client_archive/_delete_form.html.twig') }}
{% endblock %}

templates/client_archive/index.html.twig
{% extends 'front.html.twig' %}

{% block title %}Archive index{% endblock %}

{% block body %}
    <h1>Archive index</h1>
    

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Image</th>
                <th>Description</th>
                <th>Date_creation</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for archive in archives %}
            <tr>
                <td>{{ archive.id }}</td>
                <td>{{ archive.image }}</td>
                <td>{{ archive.description }}</td>
                <td>{{ archive.dateCreation ? archive.dateCreation|date('Y-m-d') : '' }}</td>
                <td>
                    <a href="{{ path('app_client_archive_show', {'id': archive.id}) }}">show</a>
                    
                </td>
            </tr>
        {% else %}
        
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        
        </tbody>
        
    </table>

     <button type="button" class="btn btn-primary" onclick="window.location.href='{{ path('generator_service_reservation') }}'">PDF</button>
{% endblock %}

templates/client_archive/new.html.twig
{% extends 'front.html.twig' %}

{% block title %}New Archive{% endblock %}

{% block body %}
    <h1>Create new Archive</h1>

    {{ include('client_archive/_form.html.twig') }}

    <a href="{{ path('app_client_archive_index') }}">back to list</a>
{% endblock %}

templates/client_archive/show.html.twig
{% extends 'front.html.twig' %}

{% block title %}Archive{% endblock %}

{% block body %}
    <h1>Archive</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ archive.id }}</td>
            </tr>
            <tr>
                <th>Image</th>
                <td>{{ archive.image }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ archive.description }}</td>
            </tr>
            <tr>
                <th>Date_creation</th>
                <td>{{ archive.dateCreation ? archive.dateCreation|date('Y-m-d') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_client_archive_index') }}">back to list</a>

   
{% endblock %}